### ISSUE TITLE
When the target of best path method is a rum, the rum gain is computed twice in the main logic.

### ISSUE THREAD

**Issue by zliu06** [WenqinSHAO/caribbean#14]
When the target of best path method is a rum, the rum gain is computed twice.
It is firstly computed in the move and rotate of the ship.
It is then added after calling this function.

**Comment by WenqinSHAO** [comment]
According to line 556 https://github.com/WenqinSHAO/caribbean/blob/master/src/Player.java#L556
You've already fixed this bug ;)

**Comment by zliu06** [comment]
https://github.com/WenqinSHAO/caribbean/commit/aee7ba3bf9a9b4d32698e665786afadd92fae200
Actually there is another bug relate to this point.
